

instructions = {
    "print": "Функція print дозволяє виводити текст або значення змінних на екран.",
    "len": "Функція len повертає кількість елементів в ітерабельному об’єкті, такому як рядок, список або кортеж.",
    "type": "Функція type повертає тип об’єкта, що переданий як аргумент.",
    "input": "Функція input дозволяє користувачу вводити дані, які потім повертаються у вигляді рядка.",
    "str": "Функція str перетворює будь-який об’єкт у рядковий формат.",
    "int": "Функція int перетворює значення на ціле число.",
    "float": "Функція float перетворює значення на число з плаваючою комою.",
    "list": "Функція list створює список з ітерабельного об’єкта.",
    "dict": "Функція dict створює словник, який зберігає дані у вигляді пар ключ-значення.",
    "set": "Функція set створює множину, яка містить лише унікальні елементи.",
    "sum": "Функція sum обчислює суму всіх елементів ітерабельного об’єкта.",
    "max": "Функція max повертає найбільший елемент з ітерабельного об’єкта.",
    "min": "Функція min повертає найменший елемент з ітерабельного об’єкта.",
    "abs": "Функція abs повертає абсолютне значення числа (модуль).",
    "round": "Функція round округлює число до заданої кількості десяткових знаків.",
    "sorted": "Функція sorted повертає відсортовану копію ітерабельного об’єкта.",
    "reversed": "Функція reversed дозволяє перебирати елементи у зворотньому порядку.",
    "range": "Функція range створює об’єкт послідовності чисел для використання у циклах.",
    "map": "Функція map застосовує функцію до кожного елемента ітерабельного об’єкта.",
    "filter": "Функція filter відфільтровує елементи ітерабельного об’єкта за заданою умовою.",
    "zip": "Функція zip поєднує декілька ітерабельних об’єктів в один.",
    "enumerate": "Функція enumerate додає індекси до ітерабельного об’єкта, повертаючи пари (індекс, елемент).",
    "all": "Функція all повертає True, якщо всі елементи ітерабельного об’єкта є істинними або порожні.",
    "any": "Функція any повертає True, якщо хоча б один елемент ітерабельного об’єкта є істинним.",
    "eval": "Функція eval виконує Python-вираз, переданий як рядок.",
    "exec": "Функція exec виконує Python-код, переданий як рядок.",
    "isinstance": "Функція isinstance перевіряє, чи є об’єкт екземпляром вказаного класу.",
    "id": "Функція id повертає унікальний ідентифікатор для об’єкта.",
    "hex": "Функція hex перетворює ціле число у шістнадцятковий рядок.",
    "bin": "Функція bin перетворює ціле число у двійковий рядок.",
    "oct": "Функція oct перетворює ціле число у вісімковий рядок.",
    "ord": "Функція ord повертає Unicode-значення символу.",
    "chr": "Функція chr повертає символ за його Unicode-значенням.",
    "open": "Функція open відкриває файл для читання або запису.",
    "close": "Функція close закриває відкритий файл.",
    "read": "Функція read читає дані з файлу.",
    "write": "Функція write записує дані у файл.",
    "append": "Функція append додає елемент в кінець списку.",
    "pop": "Функція pop видаляє та повертає елемент за вказаним індексом зі списку.",
    "remove": "Функція remove видаляє перший знайдений елемент зі списку за вказаним значенням.",
    "copy": "Функція copy створює поверхневу копію списку або словника.",
    "clear": "Функція clear видаляє всі елементи зі списку, словника або множини.",
    "split": "Функція split розбиває рядок на список за вказаним роздільником.",
    "join": "Функція join об’єднує елементи списку в рядок з вказаним роздільником.",
    "strip": "Функція strip видаляє пробіли або інші символи з початку та кінця рядка.",
    "replace": "Функція replace замінює підрядок у рядку на інше значення.",
    "capitalize": "Функція capitalize перетворює перший символ рядка на верхній регістр.",
    "lower": "Функція lower перетворює всі символи рядка на нижній регістр.",
    "upper": "Функція upper перетворює всі символи рядка на верхній регістр.",
    "title": "Функція title перетворює перший символ кожного слова на верхній регістр.",
    "find": "Функція find повертає індекс першого входження підрядка у рядок.",
    "count": "Функція count повертає кількість входжень підрядка у рядку або елемента у списку.",
    "index": "Функція index повертає індекс першого входження елемента в ітерабельному об’єкті.",
    "extend": "Функція extend додає елементи зі списку в кінець іншого списку.",
    "insert": "Функція insert вставляє елемент у список за вказаним індексом.",
    "update": "Функція update оновлює словник з іншого словника або списку пар (ключ, значення).",
    "get": "Функція get повертає значення за вказаним ключем у словнику.",
    "items": "Функція items повертає список пар (ключ, значення) у словнику.",
    "keys": "Функція keys повертає список усіх ключів у словнику.",
    "values": "Функція values повертає список усіх значень у словнику."
}



links = {
    "print": "https://docs.python.org/3/library/functions.html#print",
    "len": "https://docs.python.org/3/library/functions.html#len",
    "type": "https://docs.python.org/3/library/functions.html#type",
    "input": "https://docs.python.org/3/library/functions.html#input",
    "str": "https://docs.python.org/3/library/functions.html#func-str",
    "int": "https://docs.python.org/3/library/functions.html#int",
    "float": "https://docs.python.org/3/library/functions.html#float",
    "list": "https://docs.python.org/3/library/functions.html#func-list",
    "dict": "https://docs.python.org/3/library/functions.html#func-dict",
    "set": "https://docs.python.org/3/library/functions.html#func-set",
    "sum": "https://docs.python.org/3/library/functions.html#sum",
    "max": "https://docs.python.org/3/library/functions.html#max",
    "min": "https://docs.python.org/3/library/functions.html#min",
    "abs": "https://docs.python.org/3/library/functions.html#abs",
    "round": "https://docs.python.org/3/library/functions.html#round",
    "sorted": "https://docs.python.org/3/library/functions.html#sorted",
    "reversed": "https://docs.python.org/3/library/functions.html#reversed",
    "range": "https://docs.python.org/3/library/functions.html#func-range",
    "map": "https://docs.python.org/3/library/functions.html#map",
    "filter": "https://docs.python.org/3/library/functions.html#filter",
    "zip": "https://docs.python.org/3/library/functions.html#zip",
    "enumerate": "https://docs.python.org/3/library/functions.html#enumerate",
    "all": "https://docs.python.org/3/library/functions.html#all",
    "any": "https://docs.python.org/3/library/functions.html#any",
    "eval": "https://docs.python.org/3/library/functions.html#eval",
    "exec": "https://docs.python.org/3/library/functions.html#exec",
    "isinstance": "https://docs.python.org/3/library/functions.html#isinstance",
    "id": "https://docs.python.org/3/library/functions.html#id",
    "hex": "https://docs.python.org/3/library/functions.html#hex",
    "bin": "https://docs.python.org/3/library/functions.html#bin",
    "oct": "https://docs.python.org/3/library/functions.html#oct",
    "ord": "https://docs.python.org/3/library/functions.html#ord",
    "chr": "https://docs.python.org/3/library/functions.html#chr",
    "open": "https://docs.python.org/3/library/functions.html#open",
    "close": "https://docs.python.org/3/library/functions.html#close",
    "read": "https://docs.python.org/3/library/io.html#io.IOBase.read",
    "write": "https://docs.python.org/3/library/io.html#io.IOBase.write",
    "append": "https://docs.python.org/3/library/stdtypes.html#mutable-sequence-types",
    "pop": "https://docs.python.org/3/library/stdtypes.html#mutable-sequence-types",
    "remove": "https://docs.python.org/3/library/stdtypes.html#mutable-sequence-types",
    "copy": "https://docs.python.org/3/library/stdtypes.html#dict.copy",
    "clear": "https://docs.python.org/3/library/stdtypes.html#mutable-mapping-types",
    "split": "https://docs.python.org/3/library/stdtypes.html#str.split",
    "join": "https://docs.python.org/3/library/stdtypes.html#str.join",
    "strip": "https://docs.python.org/3/library/stdtypes.html#str.strip",
    "replace": "https://docs.python.org/3/library/stdtypes.html#str.replace",
    "capitalize": "https://docs.python.org/3/library/stdtypes.html#str.capitalize",
    "lower": "https://docs.python.org/3/library/stdtypes.html#str.lower",
    "upper": "https://docs.python.org/3/library/stdtypes.html#str.upper",
    "title": "https://docs.python.org/3/library/stdtypes.html#str.title",
    "find": "https://docs.python.org/3/library/stdtypes.html#str.find",
    "count": "https://docs.python.org/3/library/stdtypes.html#str.count",
    "index": "https://docs.python.org/3/library/stdtypes.html#str.index",
    "extend": "https://docs.python.org/3/library/stdtypes.html#mutable-sequence-types",
    "insert": "https://docs.python.org/3/library/stdtypes.html#mutable-sequence-types",
    "update": "https://docs.python.org/3/library/stdtypes.html#dict.update",
    "get": "https://docs.python.org/3/library/stdtypes.html#dict.get",
    "items": "https://docs.python.org/3/library/stdtypes.html#dict.items",
    "keys": "https://docs.python.org/3/library/stdtypes.html#dict.keys",
    "values": "https://docs.python.org/3/library/stdtypes.html#dict.values"
}
